ARG ARCH=RISCV
FROM gem5-dev:$ARCH

RUN rm -rf /usr/local/src \
 && apt install -y libprotobuf23 libgoogle-perftools4 libpython3.9 \
 && apt purge -y build-essential git m4 scons zlib1g-dev libprotobuf-dev protobuf-compiler libprotoc-dev libgoogle-perftools-dev \
 && apt autoremove -y

CMD [ "gem5", "--help" ]
